# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest, r: 'devel', http-user-agent: 'release'}
          # use 4.1 to check with rtools40's older compiler
          - {os: windows-latest, r: '4.1'}

          - {os: ubuntu-latest,   r: '3.0.0'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - name: Configure git
        run: git config --global core.autocrlf false

      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - name: Install macOS dependencies
        if: runner.os == 'macOS'
        run : |
          brew install automake netcdf udunits

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install -y libnetcdf-dev libudunits2-dev

      - name: Install Windows RTools40 dependencies
        if: runner.os == 'Windows' && matrix.config.r == '4.1'
        run: |
          pacman -Sy
          pacman -S --noconfirm mingw-w64-{i686,x86_64}-{netcdf,udunits}
        shell: sh

# Avoid R package dependencies by using a simple test script:
      - name: Check RNetCDF
        if: runner.os != 'Windows' || matrix.config.r != '4.1'
        env:
          _R_CHECK_FORCE_SUGGESTS_: false
        run: |
          echo ::group::Build RNetCDF
          R CMD build .
          echo ::endgroup::
          echo ::group::Check RNetCDF
          R CMD check --no-manual RNetCDF_*.*-*.tar.gz
          echo ::endgroup::
        shell: sh

      - name: Check RNetCDF on multiarch Windows
        if: runner.os == 'Windows' || matrix.config.r == '4.1'
        env:
          _R_CHECK_FORCE_SUGGESTS_: false
        run: |
          echo ::group::Build RNetCDF
          R CMD build .
          echo ::endgroup::
          echo ::group::Check RNetCDF
          R CMD check --no-manual --extra-arch=i386 RNetCDF_*.*-*.tar.gz
          echo ::endgroup::
        shell: sh

      - name: Upload check directory
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.config.os }}_r-${{ matrix.config.r }}_check
          path: RNetCDF.Rcheck/
          retention-days: 5

